from typing import Protocol

from golf_domain.ids import SessionId, UserId
from golf_domain.session import Session


class SessionRepository(Protocol):
    async def add(self, session: Session) -> None: ...
    async def get(self, session_id: SessionId) -> Session: ...
    async def list_for_user(self, user_id: UserId | None) -> list[Session]: ...
    async def update(self, session: Session) -> None: ...
