from typing import Protocol

from golf_domain.ids import SessionId, ShotId
from golf_domain.shot import Shot


class ShotRepository(Protocol):
    async def add(self, shot: Shot) -> None: ...
    async def add_many(self, shots: list[Shot]) -> None: ...
    async def get(self, shot_id: ShotId) -> Shot: ...
    async def list_by_session(self, session_id: SessionId) -> list[Shot]: ...
    async def update(self, shot: Shot) -> None: ...
    async def delete(self, shot_id: ShotId) -> None: ...
